agent:
  enabled: false

controller:
  serviceType: NodePort
  nodePort: 30880

  admin:
    existingSecret: jenkins-admin-secret

  numExecutors: 2

  initContainerEnv:
    - name: JAVA_TOOL_OPTIONS
      value: "-Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=30000"

  installPlugins:
    - workflow-aggregator
    - git
    - configuration-as-code

  additionalPlugins:
    - ssh-agent
    - workflow-cps-global-lib

  JCasC:
    configScripts:
      global-pipeline-libraries: |
        unclassified:
          globalLibraries:
            libraries:
              - name: "shared-libraries"
                defaultVersion: "main"
                retriever:
                  modernSCM:
                    scm:
                      git:
                        remote: "https://github.com/diegofnunesbr/shared-libraries.git"
