apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgCagntN54zFDjIjvPuLU3vKLYvfvM8Yq4k+Cx54CASQ71AqMA4qWsP/5ssTgwj4zvS1w0ze1vBAC50UBDKHx/Sl3XDwejc1TrPjHUAZS2PppC0SVSOxR2evuvX4FM+eEvTkFzRnG4mYkiG792BvwLHU+Kt6Ao7RfJfoPQHrDaM90xWJyeSRUGji+1scQk62mHw2H8YGkcAbzL3p1zybc5jIwlis5RAYD6ujzLzGomK1Kug8PaAjRDQUk+pBEeqj/pa1W78lyuHXWIeejlGx82wzEZCq6Wg2uNo3tVmFC+iMnOeodkInG4fhDjh8UspQbBFeg7EiYOCtc4jj58zTVm65fmN6MwNF9mguNPNIkALxVlMxeMtU8opbIU/iiUq+wLXD/LgchmEA1vO3FKkhHiPKA5GZDlG8V0sONmbbSGD0XK4vwK+Y8HV310Dm+6dW5rL43xCcnqfcCjFcU7S0ZDMw/RKrUx+tzPHwXfchjxzk76GGLThw+2i7eivBZtEpGzNMYB8bpnYPE/JIOd2ArZBrptXawKbMsYclp/OW2dbQkbQ42jnrgH7v+uOR3CBkdByY0F/T15hnQNp9yRYEOb4B4fGGGE006fJW42kJsO2qcTm8mgJijyV/YBPcFhGu1sl+HWR+/pO5AskL6aRyHe5Vork2tfYiw4i1NPrn78Bs1Z0tPuB60NtBYT7TjCquSTSvio0upj4lx+bbmQ==
    jenkins-admin-user: AgB3vEJDtzHJQZYqORWyi2w7FJ5UT0KRrgEOC9OopnpeO6Zfw1rLdCEVPVhbclQyg/L/fOewqGLWamejNxi1CyhN81C2foXGE8y72qSDZ3M0hloDEiXz8mAc2R81N7iVbOvUcT63tP197OuD9GU1xs5ucOzzc60WxfwG+Oj5/lcd/knWQGbOjlFLdXKYok4Zx6rRlrmA9ALs+nO9xVmxkLK/qgn5W2GqnLSjF4JmKcqZrKe8dWdgprrwNlTK3HPV+ZA5gAnkyBPKB3Kk01TtUoN33D51fI4ufKCZ5x8ZZef01Kf7g7ftMIFN+5/SQO/gJuGXq4naCLaGwrusyvud6SECyq4uH6BUinvpUUBvv2S2NaW9qwkjpXpe4qO62Ku1zehRnrPkGnE7qoaPI1+aVEKrP/hv6i8RGHZGZtqjqwn2H26eNkJptQHPAIZhVQWqPhUVnlyb9irh2zBwc3/SUUgyHm6OMpixsDR5Qz+gkbT47Y+VgM1i9VgEbhZp8ESHzxH99pfoM/95WFuA7SMRbQ+vypAHpP1m3N5DilTCOwci0xZ+8ht8X0gi1Ak5ipeNKPjEmCq8D15y6V5D3/IKMuVJZW9Ms1XyQiI6LVIAZ+otWVChzScYksahTdAwfiLXXPy2RHc6zSfDL623U/FBtrIwKTLMy6hI7uh6MlqIyI4+qmqy7fEPmmKACMP/F8VaZHNQIfE/yA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jenkins-admin-secret
      namespace: jenkins
    type: Opaque

