apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jenkins-oidc
  namespace: jenkins
spec:
  encryptedData:
    clientSecret: AgB2gAKkOGjTmA43sBR/quv3mL3Z/pcYJdiP/YOGUCyLvgwEh5fimLB75lRxEkNvcbPCxnUFleD99zX/4YpoY6xUGtp5hDq7ZyoQejW+EvNSV0idQmB1/IiYvfo5EGblx2aYFDnzNqXP8VsGYAIIFiGLnc/do3pX2zxoq6b83kQe7kh4aq/FdiA7WAou4ek4HAd72RRIgVU5gIDEuTNKkNs2UfFIxMcBaITn4+k85I+66k/EuZQRqliYWlG0XPnq5D0TtQZ7NnOvoyJsKFKrMcX6ZorkBOiRiuHIWvvolW/dhjdeHYE7GRv7J5mSvBL6BHw1E7ODdWEk+HVeS/PaREzKuTwJZA2Azz6kVw5Kvy8fsz0QUueeF6MwI+cpiyLErFrC37S7bA5AwR5VYXdomjmHRSt9UhaiaGhNJqyBOj/boBIFPOkM4CMrFQFktwi0n9kCzuekZgRHe8zD/JVZJiDWDH0UNJog4Gjx5CiRE0+5UbA6hxCj8xeSptEDZ1rj6USKm+bO+oYKlBf0YkV0tspfqjUfsSXjE40uVJtH8iRa6/M69amy0B7d3d/N9903lRdZ7FpiWT4nCaNDkeCyPSuY4DyRwUO2o8Y7v1dOiUA8gelISn094jbSJ2RNI3EboSHJgYGIjW8l9Ozw8VKZqAAifdt8qdZbEVJlJfNYfRIdge5qvrfrd96W1do8p/JeWKU51v6avVToAV32qm5qsJLjYjWUskYcbLiyz7YPzQ1nfc+fw/LebV5BUJFyovRVCPrvr8Os8KLrQVS7DJ3Zlhkz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jenkins-oidc
      namespace: jenkins
    type: Opaque

