apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  encryptedData:
    jenkins-admin-password: AgAO042NWrAm7Ur1tKhoj+SopOpqPUbWctGfd45oXWWx01CSHVIRw4oG13FPXlkIPwzGQhPpqu+N+JLzsTwjV5qP5V9COjEi2MwekFBDR0ys6MwHWJ0yVmy/cIpZ1DA+LeO7px4QKERQiYGcU+AJE7CcG7771hNnZReEiY1ctQ6osNcxDRro2TyvV9Zlkk/89/+Q0KlkkE/ma2PW5tD9RZT2ryp7DfQoFanuCAVlbToEzNGb3eK6wYE4DCRk97KMn2defaMzUEa2VoPnmcAgTleSeX2cGzHCYJ0hgF+0GZB+ZplqLhstgh8xl+RrxraVb9prZoLyjkwN4vgBRJqz2T0eJ92PpalUhzDSFT1hlrRR6JdxWD+WLrDAN2UHeXlfE9J7ra8dlVZacPA1wetzJ/Kc+jiO4PSheCQz7mVTWraaeW2r0Qu9zrnFk3B9vuBQFlbNKJ0SFj82KUb3vOKi2kFMk4A2YolZD04t5SvvbHzD5t8QKe8dUqJ6cwpBoPH6xXovStsgsK+O31NEIxfmW72g8Qdak40dVWakkWEnBXCjiNVNSFav1BtX0GaAhuL62j+B5fElkhvIZhX3a4gCFzfzICot+/IFKvXw/FInz28DDWAXGEGLFt7hibTD4A8mLUSqBQIPKqV4utPhzE09owYmP0D9raI0qUiF9fJ7KnqGdlCAJGc271ylxrxMSvMBADjFdaBanjTwjVtsOSabIrGMxyLAQP28dxo=
    jenkins-admin-user: AgB1RTz8cNx+tqB6gu2ML2yhJxf8aajHiLQ03DzO/bEbSqKo5+XBqc7jVQQYj2IizJhz2WG+uLFqfU6gIMRCbhWbWDnlHddggv/siMLoTJH0NJLUnnENTezCsfLA5On3LjXSHFzVJWGvj5o3fQHRyc7XlcijrZ2rilzZCw3doN21dKzQUZiXxqSksd4cZOKvNk3E9pf0UujJuK7Ry39J3B9zAeASNqJx/ij5/k7w+7dWsu68KjifvMpoxVz0wAQJDVGhLU+ADdJizkcNA99gWgVrbIkTmyDK/wN0p9ZcK+VDKbATudgomJ/KC+FIx2+FJsbV05ujpW988Y0yxTzQvp/wNdrX5Iy+AGYkxdq1vZMt76nht5fjLEEbYWnGyx99ixoYbumfU7iZIheWlSIBujk2I5ebE94YPIWdug129e3CAFHsg/3itkF+d12zZNH5CtGQqp/QIxSdmU4uj5/T7WSCzEJqhwkwNEvdJDRKp83vdKepmlASnMtydDgOsIKoMwl+7Th1n31wNqEWZsfPNEyfJCgZzidXqr0UPbKZZJIOv5G4GHDG9RWRV0FPVT+zXWzvWBJc+g8xG/Z58WsJfscL7EDI1ZnAH8OOAIxz+UB06cVqDUudmZ2L61aKqkFy6BGmODFYglFnZk+97evMpk1khiIlPjSnHk0DL/KCr4/NkT85Bi1F43szK22cfE+p1UY/Cr6rrQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: jenkins-admin-secret
      namespace: jenkins
    type: Opaque

